version: "3.8"

# GPU service (uncomment to use)
#services:
#  ai-server:
#    container_name: ai-server
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        USE_GPU: true
#    runtime: nvidia
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
#    env_file:
#      - .env
#    ports:
#      - "8001:8001"

# CPU service
services:
  ai-server-cpu:
    container_name: ai-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_GPU: false
    env_file:
      - .env
    ports:
      - "8001:8001"
