services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    # 데이터 보존 설정 -> 60초마다 키가 변경되면 디스크에 저장
    # 프로젝트 상 작업 결과를 몽고디비를 활용 -> 빠른 전달에 집중해서 AOF가 아닌 RDB 복구 방식 선택
    command: redis-server --save 60 1 --maxmemory 128mb --maxmemory-policy volatile-lru --loglevel warning

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  backend:
    build: .
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-8000} --workers 1 --loop asyncio --http h11 --timeout-keep-alive 30
    volumes:
      - .:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env

  celery:
    build: .
    container_name: celery
    command: >
      celery -A app.core.tasks.celery_app.celery_app worker
      --loglevel=info
      --concurrency=1
      --pool=prefork
      --prefetch-multiplier=1
      -Q celery
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongo
    env_file:
      - .env